"""combine merchant and admin tables

Revision ID: 529925c0bf40
Revises: 570070a1b28b
Create Date: 2019-09-30 22:23:42.294743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '529925c0bf40'
down_revision = '570070a1b28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_inventory_merchant_id_merchant'), table_name='inventory', type_='foreignkey')
    op.drop_table('merchant')
    op.create_foreign_key(op.f('fk_inventory_admin_id_admin'), 'inventory', 'admin', ['admin_id'], ['id'])
    op.drop_column('inventory', 'merchant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.Column('admin_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant'))
    )
    op.add_column('inventory', sa.Column('merchant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_inventory_admin_id_admin'), 'inventory', type_='foreignkey')
    op.create_index('fk_inventory_merchant_id_merchant', 'inventory', ['merchant_id'], unique=False)
    op.drop_column('inventory', 'admin_id')
    # ### end Alembic commands ###
