"""add merchant foreign key to inventory

Revision ID: 561a64ffd73f
Revises: 06170fcc6c51
Create Date: 2019-06-23 16:28:32.917174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561a64ffd73f'
down_revision = '06170fcc6c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('merchant_id', sa.Integer()))
    op.create_foreign_key(None, 'inventory', 'merchant', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'merchant_id')
    # ### end Alembic commands ###
