"""empty message

Revision ID: 570070a1b28b
Revises: 71c17be7e0da
Create Date: 2019-08-17 22:47:59.672503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570070a1b28b'
down_revision = '71c17be7e0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.Unicode(length=128), nullable=True))
    op.add_column('user', sa.Column('password', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###
