"""add_api_key_table

Revision ID: 71c17be7e0da
Revises: aa3dcd82b926
Create Date: 2019-08-17 20:35:01.786510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c17be7e0da'
down_revision = 'aa3dcd82b926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Unicode(length=128), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_api_key_admin_id_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key')
    # ### end Alembic commands ###
