"""empty message

Revision ID: 83c62c44b372
Revises: 3205ff9e367b
Create Date: 2019-08-12 23:24:22.049429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c62c44b372'
down_revision = '3205ff9e367b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carts')
    op.add_column('carted_items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'carted_items', type_='foreignkey')
    op.create_foreign_key(None, 'carted_items', 'users', ['user_id'], ['id'])
    op.drop_column('carted_items', 'cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carted_items', sa.Column('cart_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'carted_items', type_='foreignkey')
    op.create_foreign_key(None, 'carted_items', 'carts', ['cart_id'], ['id'])
    op.drop_column('carted_items', 'user_id')
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
