"""Add admin_id to User

Revision ID: 97f1e18cf03b
Revises: ef8ee7b77798
Create Date: 2019-10-23 23:31:51.526468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f1e18cf03b'
down_revision = 'ef8ee7b77798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin_id')
    # ### end Alembic commands ###
