"""add_admin_model_with_merchant_fkey

Revision ID: aa3dcd82b926
Revises: 98b46e0252b6
Create Date: 2019-08-17 18:22:36.777142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3dcd82b926'
down_revision = '98b46e0252b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin'))
    )
    op.add_column('merchant', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_merchant_admin_id_admin'), 'merchant', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_merchant_admin_id_admin'), 'merchant', type_='foreignkey')
    op.drop_column('merchant', 'admin_id')
    op.drop_table('admin')
    # ### end Alembic commands ###
