"""empty message

Revision ID: cf67602fa17b
Revises: 77b61029e92b
Create Date: 2019-08-12 20:17:22.490502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf67602fa17b'
down_revision = '77b61029e92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
