"""Use hashed api keys

Revision ID: ef8ee7b77798
Revises: 529925c0bf40
Create Date: 2019-10-01 22:35:55.443570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8ee7b77798'
down_revision = '529925c0bf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('key_code', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'key_code')
    # ### end Alembic commands ###
